DROP DATABASE IF EXISTS Invoice;
CREATE DATABASE Invoice;
use Invoice;

create table Invoice
	( INVOICEID INT not null AUTO_INCREMENT,
	INVOICEDATETIME DATETIME not null,
	DESCRIPTION VARCHAR(100) not null,
	TITLE VARCHAR(100) not null,
	AMOUNT DECIMAL(6,2) not null,
	GROUPID INT not null,
	PHOTOLINK VARCHAR(100),
	CONSTRAINT INVOICE_PK PRIMARY KEY (INVOICEID)
	);
    
INSERT INTO Invoice (INVOICEDATETIME, DESCRIPTION, TITLE, AMOUNT, GROUPID) VALUES("2017-06-15 09:34:21", "Movie", "Movie Outing", 200, 1);
INSERT INTO Invoice (INVOICEDATETIME, DESCRIPTION, TITLE, AMOUNT, GROUPID) VALUES("2019-06-15 09:34:21", "Movie", "Movie Outing", 300, 1);
    
CREATE TABLE UserInvoice
( UserID VARCHAR(100) NOT NULL,
  InvoiceID INT NOT NULL,
  Creator TINYINT(1) NOT NULL,
  CONSTRAINT UserInvoice_PK PRIMARY KEY (USERID, INVOICEID));

INSERT INTO UserInvoice VALUES("123abc", 1, 1);