DROP DATABASE IF EXISTS UserGrpOuting;
CREATE DATABASE UserGrpOuting;
use UserGrpOuting;

CREATE TABLE UserGrpOuting 
	(USERID VARCHAR(100) not null,
	 GROUPID VARCHAR(100) not null,
	CONSTRAINT USERGRPOUTING_PK PRIMARY KEY (USERID, GROUPID));


INSERT INTO UserGrpOuting VALUES("123abc", "1");
INSERT INTO UserGrpOuting VALUES("456abc", "1");
INSERT INTO UserGrpOuting VALUES("123abc", "2");
     
