DROP DATABASE IF EXISTS Settlement;
CREATE DATABASE Settlement;
USE Settlement;

CREATE TABLE Settlement
	( UserID VARCHAR(50) NOT NULL,
	InvoiceID VARCHAR(100) NOT NULL,
	TransactionID VARCHAR(100) NOT NULL,
	SettlementDateTime DATETIME NOT NULL,
	CONSTRAINT SETTLEMENT_PK PRIMARY KEY (USERID, INVOICEID));

INSERT INTO Settlement VALUES("Hardyanto", "Invoice123", "T123", "2017-06-16 09:34:21");