DROP DATABASE IF EXISTS User;
CREATE DATABASE User;
use User;

CREATE TABLE user
( USERID VARCHAR(100) NOT NULL,
  USERNAME VARCHAR(100) NOT NULL,
  PWD VARCHAR(100) NOT NULL,
  CONSTRAINT USER_PK PRIMARY KEY (USERID) );
  
INSERT INTO User VALUES("123abc", "Hardyanto", "Hardy123");
INSERT INTO User VALUES("456abc", "HongRen", "HongRen123");
INSERT INTO User VALUES("789abc", "Ram", "Ram123");
INSERT INTO User VALUES("123ccc", "Amanda", "Amanda123");